Repository atlp-rwanda/eagles-bn-backend, pull requests merged in 2020-11, with the labels that each got.

#22 fix trips,accommodations and locations seeders
  package.json
  src/database/migrations/20201021103153-create-room.js
  src/database/migrations/20201021103153-create-trip.js
  src/database/seeders/20201014101122-Trip.js
  src/database/seeders/20201014101122-accommodation.js
  src/database/seeders/20201014101122-location.js
  src/database/seeders/20201014101122-room.js
  src/tests/index.test.js
  src/tests/logout.test.js
Labels: chore, ready for review

#23 #175226667 create and update trip request
  package.json
  src/config/passport.js
  src/controllers/trip.js
  src/controllers/user.js
  src/database/migrations/20201021103153-create-trip.js
  src/database/migrations/20201021103153-create-user.js
  src/database/models/trip.js
  src/database/models/user.js
  src/database/seeders/20201014101122-User.js
  src/index.js
  src/middlewares/trip.js
  src/middlewares/verifyToken.js
  src/routes/index.js
  src/routes/trip.js
  src/routes/user.js
  src/tests/index.test.js
  src/tests/sendEmail.test.js
  src/tests/trip.test.js
  src/utils/catcher.js
  src/validators/trip.js
  swagger.json
Labels: feature, ready for review

#20 feat (user roles)
  package.json
  src/controllers/user.js
  src/database/migrations/20201021103153-create-user.js
  src/database/models/user.js
  src/database/seeders/20201014101122-User.js
  src/helpers/jwt_helper.js
  src/helpers/managers.js
  src/helpers/roles.js
  src/middlewares/user.js
  src/routes/user.js
  src/tests/index.test.js
  src/tests/roles.test.js
  src/validators/user.js
  swagger.json
Labels: feature, ready for review

#27 User should be able to comment and delete his comment
  .env.example
  .jshintrc
  package.json
  src/controllers/comment.js
  src/controllers/user.js
  src/database/migrations/20201021103153-create-user.js
  src/database/migrations/20201101175632-create-comment.js
  src/database/models/Accommodations.js
  src/database/models/Locations.js
  src/database/models/Rooms.js
  src/database/models/Trips.js
  src/database/models/comment.js
  src/database/models/location.js
  src/database/models/trip.js
  src/database/models/user.js
  src/database/seeders/20201014101122-User.js
  src/helpers/eventEmitter.js
  src/helpers/jwt_helper.js
  src/helpers/managers.js
  src/helpers/roles.js
  src/middlewares/user.js
  src/routes/index.js
  src/routes/user.js
  src/tests/comment.test.js
  src/tests/index.test.js
  src/tests/roles.test.js
  src/tests/trip.test.js
  src/tests/user.test.js
  src/validators/comment.js
  src/validators/user.js
  swagger.json
Labels: ready for review

#29 Bg accommodation room roles
  package.json
  src/database/seeders/20201014101122-User.js
  src/middlewares/user.js
  src/routes/accomodation.js
  src/routes/room.js
  src/tests/mock-user.data.js
Labels: bug, ready for review

#31 #175226677 add search in trip requests
  .prettierrc.json
  package.json
  src/controllers/accomodation.js
  src/controllers/booking.js
  src/controllers/comment.js
  src/controllers/room.js
  src/controllers/trip.js
  src/controllers/user.js
  src/routes/accomodation.js
  src/routes/index.js
  src/routes/trip.js
  src/routes/user.js
  src/tests/booking.test.js
  src/tests/comment.test.js
  src/tests/trip.test.js
  src/tests/user.test.js
  src/validators/booking.js
  src/validators/trip.js
  src/validators/user.js
  swagger.json
Labels: feature, ready for review

#34 Ft like unlike accommodation
  Profile Page Settings.docx
  src/controllers/accomodation.js
  src/controllers/user.js
  src/database/migrations/20201110183540-create-like.js
  src/database/migrations/20201111132917-create-feedback.js
  src/database/models/feedback.js
  src/database/models/like.js
  src/helpers/cloudinary-upload.js
  src/routes/accomodation.js
  src/tests/accommodation/accommodation.test.js
  src/tests/accommodation/trip.data.js
  src/tests/logout.test.js
  src/validators/user.js
  swagger.json
  {
Labels: ready for review

#33 fix(heroku): deployment pipeline
  .env.example
  src/config/redis_config.js
  src/controllers/trip.js
Labels: bug, ready for review

#30 feat(ft-update-trip-status): update trip status
  package.json
  src/controllers/trip.js
  src/database/models/user.js
  src/index.js
  src/middlewares/trip.js
  src/routes/trip.js
  src/validators/tripStatus.js
  swagger.json
Labels: feature, ready for review

#38 Users Should chat on barefoot nomad [finishes 175226686]
  package.json
  src/chatBot.html
  src/controllers/chat.js
  src/controllers/user.js
  src/database/migrations/20201108183756-create-chat.js
  src/database/models/chat.js
  src/database/models/user.js
  src/helpers/jwt_helper.js
  src/index.js
  src/middlewares/socketio.auth.js
  src/tests/chat.test.js
  src/tests/comment.test.js
Labels: ready for review

#40 Profile documentation bug fix
  swagger.json
Labels: ready for review
