Repository atlp-rwanda/eagles-bn-backend, pull requests merged in 2020-12, with the labels that each got.

#47 bg(fix-signup): fix signup
  src/controllers/user.js
  src/validators/user.js
Labels: WIP, bug

#51 fix(user): profile update
  .gitignore
  .vscode/settings.json
  dump.rdb
  package.json
  src/controllers/user.js
  src/database/migrations/20201021103153-create-user.js
  src/database/models/user.js
  src/database/seeders/20201014101122-User.js
  src/index.js
  src/middlewares/trip.js
  src/middlewares/user.js
  src/routes/index.js
  src/routes/trip.js
  src/routes/user.js
  src/tests/assets/fake.txt
  src/tests/function.test.js
  src/tests/index.test.js
  src/tests/logout.test.js
  src/tests/notification.test.js
  src/tests/oauth.test.js
  src/tests/sendEmail.test.js
  src/tests/trip.test.js
  src/tests/user.test.js
  src/validators/user.js
  storage/.gitignore
  storage/8b24iqtest_image.png
  storage/ar248ttest_image.png
  storage/dl0kijtest_image.png
  storage/xnm5ztest_image.png
  swagger.json
Labels: bug, ready for review

#53 bug(fix-trip-status): fix trip status
  src/controllers/trip.js
  src/database/seeders/20201014101122-Trip.js
  src/database/seeders/20201014101122-User.js
  src/routes/trip.js
Labels: bug
