Repository atlp-rwanda/eagles-bn-backend, pull requests merged in 2020-10, with the labels that each got.

#1 chore(node-setup): set up initial express app
  .babelrc
  .gitignore
  package.json
  src/config/index.js
  src/controllers/index.js
  src/helpers/index.js
  src/index.js
  src/middlewares/index.js
  src/models/index.js
  src/routes/index.js
  src/tests/index.js
  src/utils/index.js
  src/validators/index.js
Labels: chore, ready for review

#3 add eslint style
  .eslintrc.json
  .hound.yml
  jshintrc.yml
  package.json
  src/index.js
Labels: ready for review

#8 bugfix(deploy): add buid command
  .babelrc
  .gitignore
  .idea/.gitignore
  .idea/eagles-bn-backend.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .nyc_output/processinfo/index.json
  package.json
  src/index.js
  swagger.json
Labels: bug, ready for review

#9 feat(signup): create user
  package.json
  src/controllers/index.js
  src/controllers/users.js
  src/database/migrations/20201014100459-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/helpers/auth.js
  src/helpers/index.js
  src/index.js
  src/routes/index.js
Labels: feature, ready for review

#16 #175226657 setup docker with postgres
  .dockerignore
  .env.example
  .gitignore
  Dockerfile
  docker-compose.yml
  package.json
  src/config/passport.js
  src/database/config/config.js
  src/database/models/index.js
Labels: chore, ready for review

#14 Reset Password [175226663]
  .env.example
  package.json
  src/controllers/user.js
  src/database/migrations/20201021103153-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20201014101122-User.js
  src/helpers/auth.js
  src/helpers/index.js
  src/index.js
  src/routes/index.js
  src/tests/user.test.js
  src/validators/user.js
  swagger.json
Labels: feature, ready for review

#18 Ft send verification email 175226659
  .env.example
  .jshintrc
  jshintrc.yml
  package.json
  src/controllers/user.js
  src/database/migrations/20201021103153-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/index.js
  src/middlewares/user.js
  src/routes/user.js
  src/tests/oauth.test.js
  src/tests/sendEmail.test.js
  src/tests/user.test.js
  swagger.json
Labels: ready for review

#17 logout functionality
  .travis.yml
  package.json
  src/config/passport.js
  src/config/redis_config.js
  src/controllers/oauth.controller.js
  src/controllers/user.js
  src/database/config/config.js
  src/database/migrations/20201014100459-create-users.js
  src/database/migrations/20201021103153-create-user.js
  src/database/models/index.js
  src/database/models/user.js
  src/database/seeders/20201014101122-User.js
  src/helpers/auth.js
  src/helpers/index.js
  src/helpers/jwt_helper.js
  src/index.js
  src/middlewares/auth.js
  src/middlewares/user.js
  src/middlewares/verifyToken.js
  src/routes/auth.js
  src/routes/index.js
  src/routes/user.js
  src/tests/assets/user.js
  src/tests/index.test.js
  src/tests/login.test.js
  src/tests/oauth.test.js
  src/tests/sendEmail.test.js
  src/tests/user.test.js
  src/tests/user/logout.test.js
  src/utils/response.js
  src/validators/user.js
  swagger.json
Labels: ready for review

#21 seeds and migration for accommodation, trips, and location
  src/database/migrations/20201021103153-create-accommodation.js
  src/database/migrations/20201021103153-create-location.js
  src/database/migrations/20201021103153-create-room.js
  src/database/migrations/20201021103153-create-trip.js
  src/database/seeders/20201014101122-Trip.js
  src/database/seeders/20201014101122-accommodation.js
  src/database/seeders/20201014101122-location.js
  src/database/seeders/20201014101122-room.js
Labels: ready for review
